### PR TITLE
change ccs read score back to accuracy

### PR DESCRIPTION
**Pull request by ben-lerch**
just a little revision in light of dave's email.

### CODE REVIEW

**Comment by nlhepler** [comment]
Let's hold off on this for a moment, I'm not entirely comfortable with this change.

**Comment by nlhepler** [comment]
Okay, it reads "predicted". That's fine.

**Comment by evolvedmicrobe** [comment]
This makes no sense to me, what is going on here?  I think the read score is the more appropriate point.  

More importantly though, who is responsible for the CCS Mapping job?  This is a customer facing protocol and my understanding is that no one has verified how the QUAL values are assigned to variants in it.  @dalexander @ben-lerch do you guys know?

**Comment by nlhepler** [comment]
@evolvedmicrobe we should just redo this entire protocol, I agree. I'll let Tzvetana (or Mary now?) know we're not entirely happy with the state of CCS_Mapping and would like to have it prioritized for maintenance.

**Comment by natechols** [comment]
There are still some inconsistencies in our use of "accuracy", mostly when it should be "concordance"; this issue is just a side effect.  In this case "predicted accuracy" is okay, the only caveat is that in the CCS report, it's reported as "read score" (deliberately, after many iterations with marketing).

**Comment by evolvedmicrobe** [comment]
@nlhepler: do you know where the source code for the ccs mapping job is? I would like to take a look at these QUAL values.

**Comment by natechols** [comment]
You probably need to look at blasr (and pbalign); the pbsmrtpipe pipeline doesn't add anything beyond what these already support for CCS.

**Comment by evolvedmicrobe** [comment]
Ah, okay for some reason I thought this output a GFF of variants, I just checked the latest SMRT Link and this appears NOT to be the case.  I think we need to improve this protocol to do variant calling, I will add it to my brown bag talk.

**Comment by ben-lerch** [comment]
i believe this can be closed now

**Pull request closed without merging**
