### PR TITLE
read metadata into report modules from report specs 

### PR DESCRIPTION
**Pull request by ben-lerch**

### CODE REVIEW

**Comment by ben-lerch** [comment]
I have more metadata-related work to do, so I think we should keep this pull request open for the commits that are yet to come.

**Comment by ben-lerch** [comment]
this is close to the point where it should be merged i think. but feedback is welcome. how do we want to kill the variable plot ids? can i just go to those places in the code and remove the variables, or is there more to do?

**Comment by ben-lerch** [comment]
this should be merged this week in preparation for our transition on Aug 3rd. there's still some more work to be done (like dealing with variable plot IDs) but i think the remaining issues can be treated as separate PRs if we want.

**Comment by natechols** [comment]
Agreed, but you need to resolve the conflicts before it can be merged.

**Pull request merged**
