### PR TITLE
Coverage hgap

### PR DESCRIPTION
**Pull request by ben-lerch**
this addresses SL-523 by cloning the coverage report

### CODE REVIEW

**Comment by natechols** [comment]
We need to come up with a way to do this that doesn't involve duplicating the entire module.

**Comment by ben-lerch** [comment]
PR 237 attempts to address this by adding a new option to the tool contract that allows for specifying a different spec file- that attempt is a WIP. Is that the approach we want? I'm not sure what the long-term solution is.

**Comment by natechols** [comment]
No, that's not right either.  The code needs to be refactored to allow switching specs with minimal duplication.  There's no easy way around this that will be maintainable.

**Comment by ben-lerch** [comment]
The only way I know to tell coverage.py to use a different spec is at the TC level. Is there a different way you know of that better addresses the problem? I guess I could use guidance here.

**Comment by natechols** [comment]
As I said, the code needs to be refactored to support what we're trying to do.  If this is too much trouble I'll deal with it.

**Comment by ben-lerch** [comment]
I don't think it's too much trouble I'm just not sure what you have in mind.

**Comment by natechols** [comment]
I'll deal with it.

**Pull request closed without merging**
